apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-demo-otelcol
  labels:
    opentelemetry.io/name: opentelemetry-demo-otelcol
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/component: otelcol
    app.kubernetes.io/name: opentelemetry-demo-otelcol
    app.kubernetes.io/version: "0.133.0"
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      opentelemetry.io/name: opentelemetry-demo-otelcol
  template:
    metadata:
      labels:
        opentelemetry.io/name: opentelemetry-demo-otelcol
        app.kubernetes.io/instance: opentelemetry-demo
        app.kubernetes.io/component: otelcol
        app.kubernetes.io/name: opentelemetry-demo-otelcol
    spec:
      serviceAccountName: opentelemetry-demo
      containers:
        - name: otelcol
          image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.133.0
          imagePullPolicy: IfNotPresent
          args:
            - --config=/conf/otelcol-config.yml
          ports:
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
            - containerPort: 8888
              name: metrics
          env:
            - name: GOMEMLIMIT
              value: "160MiB"
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 100Mi
          volumeMounts:
            - name: config
              mountPath: /conf
          readinessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: config
          configMap:
            name: opentelemetry-demo-otelcol-config
            items:
              - key: otelcol-config.yml
                path: otelcol-config.yml
